// Code generated by hero.
// source: D:\project\GO\gowork\src\datastream\view\template\acceptfileus.html
// DO NOT EDIT!
package gotemplate

import (
	"my/ar/399/datastream/datalayer"
	"fmt"
	"io"
	"sort"

	"github.com/shiyanhui/hero"
)

func AcceptFileUSHandler(u datalayer.UserLogin, table map[int][]string, fname string, row int, col int, w io.Writer) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>
<html lang="fa" dir="rtl">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/StaticUI/Images/icon.ico" type="image/ico" />

    <title>بـاداده | 
      `)
	_buffer.WriteString(`
  بررسی فایل
`)

	_buffer.WriteString(`
    </title>

    <!-- Bootstrap -->
    <link href="/StaticUI/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/StaticUI/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/StaticUI/vendors/nprogress/nprogress.css" rel="stylesheet">
    `)
	_buffer.WriteString(`
    <!-- iCheck -->
    <link href="/StaticUI/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
`)

	_buffer.WriteString(`

    <!-- Custom Theme Style -->
    <link href="/StaticUI/build/css/custom.min.css" rel="stylesheet">
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 right_col menu_fixed">
          <div class="right_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="/Dashboard" class="site_title">
                <img style="padding: 6px 10px 6px 7px;height: 38px; width: auto;display: inline;" src="/StaticUI/Images/logo.png" >
                <span> بـاداده </span></a>
            </div>
            <div class="clearfix"></div>
            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <ul class="nav side-menu">
                  <li><a href="/Dashboard"><i class="fa fa-home"></i>پیش خوان</a>
                  </li>
                  <li><a><i class="fa fa-tasks"></i>سرویس ها<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Services">مشاهده سرویس های ایجاد شده</a></li>
                      <li><a href="/NewService">ایجاد سرویس جدید</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-dollar"></i>اعتبار حساب<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Credit">مشاهده اعتبار حساب</a></li>
                      <li><a href="/IncreaseCredit">افزایش اعتبار حساب</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-envelope"></i>پیام ها<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Messages">مشاهده اعلان ها</a></li>
                      <li><a href="/ContactUs">ارتباط با ما</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-user"></i>حساب کاربری<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Settings">تنظیمات حساب کاربری</a></li>
                      <li><a href="/Logout">خروج</a></li>
                    </ul>
                  </li>
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-left">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    `)
	hero.EscapeHTML(u.Fname+" "+u.Lname, _buffer)

	_buffer.WriteString(`            
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">                     
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="left_col" role="main">
          `)
	_buffer.WriteString(`
  <div class="">
      <div class="page-title">
        <div class="title_right">
          <h3 id="p-title">بررسی فایل `)
	hero.EscapeHTML(fname, _buffer)
	_buffer.WriteString(`</h3>
        </div>

      </div> 
      
      <div class="clearfix"></div>

      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2 id="pan-title">سطرهای اولیه فایل دریافت شده</h2>
              <ul class="nav navbar-left panel_toolbox">    
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">

            <form id="form" novalidate>
              <!-- start record list -->
              <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <thead>
                        <th style="width: 3%">#</th>                        
                          `)
	for i := 0; i < col; i++ {
		_buffer.WriteString(`
                            <th >
                              <input type="checkbox" class="flat" name="check_`)
		hero.EscapeHTML(fmt.Sprint(i), _buffer)
		_buffer.WriteString(`" checked="checked">
                              <br> <small>بررسی&nbsp;شود</small>
                            </th>
                                                   
                          `)
	}
	_buffer.WriteString(`
                                                
                    </thead>
                    <tbody>
                        `)
	keys := make([]int, len(table))
	ks := 0
	for k := range table {
		keys[ks] = k
		ks++
	}
	sort.Ints(keys)
	for _, k := range keys {
		t := table[k]
		_buffer.WriteString(`
                        <tr>
                            <td>`)
		hero.EscapeHTML(fmt.Sprint(k), _buffer)
		_buffer.WriteString(`</td>
                            `)
		if len(t) == col {
			for c := 0; c < col; c++ {
				_buffer.WriteString(`
                                    <td >
                                    <a>`)
				hero.EscapeHTML(t[c], _buffer)
				_buffer.WriteString(`</a>
                                    </td>
                                `)
			}
		} else {
			for c := 0; c < len(t); c++ {
				_buffer.WriteString(`
                                    <td >
                                    <a>`)
				hero.EscapeHTML(t[c], _buffer)
				_buffer.WriteString(`</a>
                                    </td>
                                `)
			}
			for c := len(t); c < col; c++ {
				_buffer.WriteString(`
                                    <td >
                                    </td>
                                `)
			}
		}
		_buffer.WriteString(`
                        </tr>
                        `)
	}
	_buffer.WriteString(`
                    </tbody>
                </table>
              </div>
              <!-- end services list -->
              <br>
              
              <div>
              <div class="radio">
                <label>
                  <input type="radio" class="flat" checked="checked" name="check_hdr" value="false"> ردیف اول به عنوان سربرگ در نظر گرفته شود و بررسی نشود
                </label>
              </div>
              <div class="radio">
                <label>
                  <input type="radio" class="flat" name="check_hdr" value="true"> ردیف اول به عنوان داده در نظر گرفته شود و بررسی شود
                </label>
              </div>
              </div>
              <div class="ln_solid"></div>
              <div class=" item form-group row">
                <label class="control-label col-md-4 col-sm-4 col-xs-12">تعیین epsilon میکرو خوشه‌ها</label>
                <div class="col-md-5 col-sm-5 col-xs-12">
                  <input dir="ltr" type="number" id="number" name="micro_eps" required="required" step="0.1" data-validate-minmax="0,999999999999999" class="form-control col-md-7 col-xs-12">
                  <!-- <input type="text" class="form-control col-md-7 col-xs-12" min="0" name="micro_eps" data-parsley-type="number" /> -->
                </div>
              </div>
              <br>
              <div class="item form-group row">
                <label class="control-label col-md-4 col-sm-4 col-xs-12">تعیین epsilon الگوریتم DBSCAN</label>
                <div class=" col-md-5 col-sm-5 col-xs-12">
                  <input dir="ltr" type="number" id="number" name="db_eps"  required="required" step="0.1" data-validate-minmax="0,999999999999999" class="form-control col-md-7 col-xs-12">
                  <!-- <input type="text" class="form-control col-md-7 col-xs-12" min="0" name="db_eps1" data-parsley-type="number" /> -->
                </div>
              </div>
              <br>
              <div id="divErr" style="display: none;" class="alert alert-warning alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
                </button>
                <div dir="rtl"><strong>خطا: </strong>
                  <div id="Err"></div>
                </div>
                
              </div>
              <div class="ln_solid"></div>
              <div class="form-group">
                <button id="btn" type="submit" class="btn btn-success btn-lg">آغاز عملیات خوشه بندی</button>
              </div>
              <br>
              <input type="hidden" name="col" value="`)
	hero.EscapeHTML(fmt.Sprint(col), _buffer)
	_buffer.WriteString(`">
            </form>
            <div id="progress" style="display: none;"  class="row">
              <br>
                <h3>میزان پیشرفت عملیات</h3>
                <br>
              <div  class="progress">
                <div  id="progress-bar" class="progress-bar progress-bar-success progress-bar-striped active" data-transitiongoal="1"></div>
              </div>
            </div>
            </div>
          </div>
        </div>
      </div>
  </div>  
`)

	_buffer.WriteString(`
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-left">
            بـاداده » سامانه برخط خوشه‌بندی داده‌های جریانی
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
    </div>

    <!-- jQuery -->
    <script src="/StaticUI/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/StaticUI/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="/StaticUI/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="/StaticUI/vendors/nprogress/nprogress.js"></script>
    `)
	_buffer.WriteString(`
  <!-- bootstrap-progressbar -->
  <script src="/StaticUI/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
  <!-- iCheck -->
  <script src="/StaticUI/vendors/iCheck/icheck.min.js"></script>

  <!-- jQuery Tags Input -->
  <script src="/StaticUI/vendors/jquery.tagsinput/src/jquery.tagsinput.js"></script>
  <!-- Switchery -->
  <script src="/StaticUI/vendors/switchery/dist/switchery.min.js"></script>
  <!-- Select2 -->
  <script src="/StaticUI/vendors/select2/dist/js/select2.full.min.js"></script>
  <!-- validator -->
  <script src="/StaticUI/vendors/validator/validator.js"></script>
`)

	_buffer.WriteString(`

    <!-- Custom Theme Scripts -->
    <script src="/StaticUI/build/js/custom.min.js"></script>
    `)
	_buffer.WriteString(`
<script>
var source = new EventSource(window.location.pathname+"/progress");
var start = true;
source.onmessage=function(event){
  if (start){
    if (event.data!="0%"){
     
      document.getElementById("form").style.display="none";
      document.getElementById("p-title").innerHTML="خوشه‌بندی داده‌های فایل"
      document.getElementById("pan-title").innerHTML="عملیات خوشه‌بندی"
      document.getElementById("progress").style.display="block";
      document.getElementById("progress-bar").style.width=event.data;
      document.body.scrollTop = 0;
      start=false;
    }
  }
  document.getElementById("progress-bar").innerHTML=event.data;
  document.getElementById("progress-bar").style.width=event.data;
}

$("#form").on("submit", function (e) {

  var b = !0;
  var c = validator.checkAll($(this));
  
  if (c){
    e.preventDefault();
    const myForm = document.getElementById("form");
    const data = $("#form").serialize();
    var $self = $(this)
    $.ajax({
        url: window.location.pathname+"/Clustering",
        type: "POST",
        data : data,
    }).success( function(res) {
      if (res.errstatus==true){        
          // document.getElementById("Err").innerHTML = res.errmsg;
          // document.getElementById("divErr").style.display="block";
          alert(res.errmsg);
      }else{
          window.location.replace(res.errmsg);
      }
    });
  }
});


</script>
`)

	_buffer.WriteString(`
    
  </body>
</html>`)
	w.Write(_buffer.Bytes())

}
