// Code generated by hero.
// source: D:\project\GO\gowork\src\datastream\view\template\addstructuredservice.html
// DO NOT EDIT!
package gotemplate

import (
	"my/ar/399/datastream/datalayer"
	"io"

	"github.com/shiyanhui/hero"
)

func AddStructuredServiceHandler(u datalayer.UserLogin, w io.Writer) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>
<html lang="fa" dir="rtl">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/StaticUI/Images/icon.ico" type="image/ico" />

    <title>بـاداده | 
      `)
	_buffer.WriteString(`
  سرویس ها
`)

	_buffer.WriteString(`
    </title>

    <!-- Bootstrap -->
    <link href="/StaticUI/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/StaticUI/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/StaticUI/vendors/nprogress/nprogress.css" rel="stylesheet">
    `)
	_buffer.WriteString(`
  <!-- iCheck -->
  <link href="/StaticUI/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
  <!-- Switchery -->
  <link href="/StaticUI/vendors/switchery/dist/switchery.min.css" rel="stylesheet">
`)

	_buffer.WriteString(`

    <!-- Custom Theme Style -->
    <link href="/StaticUI/build/css/custom.min.css" rel="stylesheet">
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 right_col menu_fixed">
          <div class="right_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="/Dashboard" class="site_title">
                <img style="padding: 6px 10px 6px 7px;height: 38px; width: auto;display: inline;" src="/StaticUI/Images/logo.png" >
                <span> بـاداده </span></a>
            </div>
            <div class="clearfix"></div>
            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <ul class="nav side-menu">
                  <li><a href="/Dashboard"><i class="fa fa-home"></i>پیش خوان</a>
                  </li>
                  <li><a><i class="fa fa-tasks"></i>سرویس ها<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Services">مشاهده سرویس های ایجاد شده</a></li>
                      <li><a href="/NewService">ایجاد سرویس جدید</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-dollar"></i>اعتبار حساب<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Credit">مشاهده اعتبار حساب</a></li>
                      <li><a href="/IncreaseCredit">افزایش اعتبار حساب</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-envelope"></i>پیام ها<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Messages">مشاهده اعلان ها</a></li>
                      <li><a href="/ContactUs">ارتباط با ما</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-user"></i>حساب کاربری<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Settings">تنظیمات حساب کاربری</a></li>
                      <li><a href="/Logout">خروج</a></li>
                    </ul>
                  </li>
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-left">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    `)
	hero.EscapeHTML(u.Fname+" "+u.Lname, _buffer)

	_buffer.WriteString(`            
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">                     
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="left_col" role="main">
          `)
	_buffer.WriteString(`
    <div class="">
        <div class="page-title">
            <div class="title_right">
              <h3>ایجاد سرویس جدید</h3>
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="row">

          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>ایجاد سرویس‌ ساختار یافته</h2>
                    <ul class="nav navbar-left panel_toolbox">    
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
              <div class="x_content">

                <h2>مرحله های زیر را به دقت طی کنید</h2><br><br>
                <!-- Tabs -->
                <form id="servform" class="form-horizontal form-label-right" novalidate>

                  <!-- step 1  -->
                  <div class="form-group">
                    <label class="col-md-3 col-sm-3 col-xs-12 control-label">مرحله اول:
                      <br>
                      <small class="text-navy">تعیین مشخصات سرویس</small>
                    </label>
                    
                    
                      <br>
                      
                      <div class="col-md-9 col-sm-9 col-xs-12">
                        <div class="row">
                          <p>برای سرویس که قصد ایجاد آن را دارید، یک نام مناسب انتخاب کنید</p>
                        </div>
                        <br>
                        <div class="item form-group">
                          <label class="control-label col-md-3 col-sm-3" for="first-name">نام سرویس<span class="required">*</span>
                          </label>
                          <div class="col-md-5 col-sm-5 col-xs-12">
                            <input type="text" name="sname" id="service-name" required="required" class="form-control col-md-4 col-xs-12">
                          </div>
                        </div>
                        <br>
                      </div>
                      <br>
                    
                  </div>
                  <div class="ln_solid"></div>
                  <!-- step 2  -->
                  <div class="form-group">
                    <label class="col-md-3 col-sm-3 col-xs-12 control-label">مرحله دوم:
                      <br>
                      <small class="text-navy"> تعیین ساختار داده سرویس</small>
                    </label>
                    
                    
                    
                      <br>
                      <div id="step2Form" class="col-md-9 col-sm-9 col-xs-12">
                        <div class="row">
                          <p>در این قسمت نام داده‌هایی که در هر درخواست به سامانه ارسال می‌شود را اتخاب کنید</p>
                          <p>
                            شما می‌توانید داده‌ها را کم و زیاد کنید.
                          </p>
                        </div>
                        <br> 
                        <div class="row">
                        <a href="#" onclick="addOption();return false";>
                          <button id="btn" type="button" class="btn btn-info">افزودن به داده‌ها</button>
                        </a>
                        </div>
                        <br> 

                        <div id="grp_0">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="in_0"><a onclick="chdelete(this);return false;"><i style="color: crimson;" class="fa fa-close"></i></a> نام داده 
                          </label>
                          <div class="item form-group">
                            <div class="col-md-5 col-sm-5 col-xs-12">
                              <input id="in_0" type="text" name="data_0" data-validate-length-range="1,20"  required="required" class="form-control col-md-4 col-xs-12">
                            </div>
                          </div>
                        </div>
                        
                        
                      </div>
                      <br>
                    
                  </div>
                  <input type="hidden" id="count" name="count" value="1">
                  <div class="item ln_solid"></div>
                  <!-- step 13  -->
                  <div class="form-group">
                    <label class="col-md-3 col-sm-3 col-xs-12 control-label">مرحله سوم:
                      <br>
                      <small class="text-navy">تعیین پارامترهای الگوریتم خوشه‌بندی</small>
                    </label>
                    
                    
                      <br>
                      
                      <div class="col-md-9 col-sm-9 col-xs-12">
                        <div class="row">
                          <p>برای انجام عملیات خوشه بندی لازم است پارامترهای زیر را مشخص کنید</p>
                        </div>
                        <br>
                        <br>
                        <div class="row">
                          <p><strong>epsilon میکرو خوشه‌ها: </strong>داده های شما قبل از خوشه بندی در میکروخوشه‌هایی دسته بندی می‌شوند. در این قسمت می‌توانید مقدار شعاع epsilon این میکرو خوشه ها را تعیین کنید.</p>
                        </div>
                        <div class="item form-group">
                          <label class="control-label col-md-3 col-sm-3" for="meps">epsilon میکروخوشه‌ها
                          </label>
                          <div class="col-md-5 col-sm-5 col-xs-12">
                            <input type="number" step="0.1" data-validate-minmax="0,999999999999999" name="meps" id="meps" required="required" class=" form-control col-md-4 col-xs-12">
                          </div>
                        </div>
                        <br>
                        <br>
                        <br>
                        <div class="row">
                          <p><strong>epsilon الگوریتم DBscan: </strong>داده های شما بعد از دسته بندی توسط الگوریتم DBscan می‌شوند. در این قسمت می‌توانید مقدار شعاع خوشه‌بندی epsilon الگوریتم DBscan را تعیین کنید.</p>
                        </div>
                        <div class="item form-group">
                          <label class="control-label col-md-3 col-sm-3" for="dbeps">epsilon الگوریتم DBscan
                          </label>
                          <div class="col-md-5 col-sm-5 col-xs-12">
                            <input  type="number" step="0.1" data-validate-minmax="0,999999999999999" name="dbeps" id="dbeps" required="required" class=" form-control col-md-4 col-xs-12">
                          </div>
                        </div>
                        <br>
                        <br>
                        <br>
                        <div class="row">
                          <p><strong>ضریب اهمیت داده قدیمی: </strong>این پارامتر اهمیت داده قدیمی را مشخص می‌کند هر چه قدر این مقدار بیشتر باشد اهمیت داده‌های قدیمی کتر است. این پارامتر باید بزرکتر از صفر باشد.</p>
                        </div>
                        <div class="item form-group">
                          <label class="control-label col-md-3 col-sm-3" for="lmbda">ضریب اهمیت داده قدیمی<span class="required">*</span>
                          </label>
                          <div class="col-md-5 col-sm-5 col-xs-12">
                            <input  type="number" step="0.1" data-validate-minmax="0,999999999999999"  name="lmbda" id="lmbda" required="required" class="form-control col-md-4 col-xs-12">
                          </div>
                        </div>
                        <br>
                      </div>
                      <br>
                    
                  </div>
                  <div class="ln_solid"></div>
                  <!-- step 4  -->
                  <div class="item form-group">
                    <label class="col-md-3 col-sm-3 col-xs-12 control-label">مرحله چهارم:
                      <br>
                      <small class="text-navy"> تعیین میزان اعتبار سرویس</small>
                    </label>
                    
                    
                    
                      <br>
                      <div id="step2Form" class="col-md-9 col-sm-9 col-xs-12">
                        
                        <div  class="item form-group">
                          <h2>مژده! </h2>
                          <p>این سرویس به مدت 90 روز به صورت رایگان برای شما فعال خواهدشد و نیازی به خرید اعتبار ندارید.</p>
                          
                        </div>
                         
                        <br>
                      </div>
                      <br>
                    
                  </div>
                  <div class="ln_solid"></div>
                  <!-- step 5  -->
                  <div class="item form-group">
                    <label class="col-md-3 col-sm-3 col-xs-12 control-label">مرحله پنچم:
                      <br>
                      <small class="text-navy"> فعال سازی سرویس</small>
                    </label>
                    
                    
                    
                      <br>
                      <div id="step2Form" class="col-md-9 col-sm-9 col-xs-12">
                        <div class="row">
                          <p>به صورت پیش فرض این سرویس غیرفعال است. می‌توانید از هم اکنون سرویس را فعال کنید.
                            در غیر این صورت سرویس شما غیرفعال خواهدبود تا زمانی که از پنل مدیریت این سرویس اقدام به فعال‌سازی سرویس نمایید.
                          </p>
                        </div>

                        
                        <label style=" display: inline">
                          <input type="checkbox" id="checkactive" name="active" onclick="checkhandle()" class="js-switch" /> <div id="checkmsg">فعال نشود </div>
                        </label>
                        <br>
                        <br>
                        <br>
                        <div class="row">
                          <p>در این قسمت می‌توانید برای این سرویس به صورت دستی تاریخی برای منقضی شدن سرویس انتخاب کنید. 
                            بعد از این تاریخ داده‌های ارسالی بررسی نخواهندشد. 
                          </p>
                        </div> 

                        <div id="grp_exptime" class="item form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="exptime"> تاریخ انقضا سرویس
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input id="exptime" dir="ltr" name="exptime" type="text" pattern="\d{4}/\d{2}/\d{2}" data-inputmask="'mask': '9999/99/99'" name="exptime"  class="optional form-control col-md-7 col-xs-12">
                          </div>
                        </div>

                        <br>
                        <br>
                        <br>
                                                
                      </div>
                      <br>
                    
                  </div>
                  <div class="ln_solid"></div>


                  <div class="form-group">
                    <button id="fbtn" type="button" class="btn btn-success">ایجاد سرویس</button>
                  </div>

                </form>
                
              </div>
            </div>
          </div>
        </div>
      </div>
`)

	_buffer.WriteString(`
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-left">
            بـاداده » سامانه برخط خوشه‌بندی داده‌های جریانی
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
    </div>

    <!-- jQuery -->
    <script src="/StaticUI/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/StaticUI/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="/StaticUI/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="/StaticUI/vendors/nprogress/nprogress.js"></script>
    `)
	_buffer.WriteString(`
  <!-- iCheck -->
  <script src="/StaticUI/vendors/iCheck/icheck.min.js"></script>
  <!-- Switchery -->
  <script src="/StaticUI/vendors/switchery/dist/switchery.min.js"></script>
  <!-- validator -->
  <script src="/StaticUI/vendors/validator/validator.js"></script>
  <!-- jquery.inputmask -->
  <script src="/StaticUI/vendors/jquery.inputmask/dist/min/jquery.inputmask.bundle.min.js"></script>
  <!-- jQuery Smart Wizard -->
  <script src="/StaticUI/vendors/jQuery-Smart-Wizard/js/jquery.smartWizard.js"></script>
  
  
`)

	_buffer.WriteString(`

    <!-- Custom Theme Scripts -->
    <script src="/StaticUI/build/js/custom.min.js"></script>
    `)
	_buffer.WriteString(`
<script> 
  var count = 2; 
  function addOption() { 
        var theForm = document.getElementById("step2Form"); 
        var newOption = document.createElement("div");
        newOption.innerHTML= ` + "`" + `<div id="grp_` + "`" + `+count+` + "`" + `">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="in_` + "`" + `+count+` + "`" + `"><a onclick="chdelete(this);return false;"><i style="color: crimson;" class="fa fa-close"></i></a> نام داده 
                          </label>
                          <div class="item form-group">
                            <div class="col-md-5 col-sm-5 col-xs-12">
                              <input id="in_` + "`" + `+count+` + "`" + `" type="text" name="data_` + "`" + `+count+` + "`" + `" required="required"  data-validate-length-range="1,20" class="form-control col-md-7 col-xs-12">
                            </div>
                          </div>
                        </div>` + "`" + `                         
        theForm.appendChild(newOption);
        document.getElementById("count").value=count
        count++;
    }

function chdelete(e){
    e.parentNode.parentNode.remove();
    // style.display='none';
  } 

function sendform() {

  var c = true;

  if (c){
    const myForm = document.getElementById("servform");
    const data = $("#servform").serialize();
    var $self = $(this)
    $.ajax({
        url: window.location.pathname,
        type: "POST",
        data : data,
    }).success( function(res) {
      if (res.errstatus==true){        
          // document.getElementById("Err").innerHTML = res.errmsg;
          // document.getElementById("divErr").style.display="block";
          alert(res.errmsg);
      }else{
          window.location.replace(res.errmsg);
      }
    });
  }
}

var form = document.getElementById("servform");

document.getElementById("fbtn").addEventListener("click", function () {
  var r = validator.checkAll($("#servform"));
  if (r){
    sendform();
  }
  
});

function checkhandle()
{
  var checkbox = document.getElementById('checkactive');
  if (checkbox.checked != true)
  {
    document.getElementById('checkmsg').innerHTML="فعال نشود";
  }else{
    document.getElementById('checkmsg').innerHTML="فعال شود";
  }
}
</script>
`)

	_buffer.WriteString(`
    
  </body>
</html>`)
	w.Write(_buffer.Bytes())

}
