// Code generated by hero.
// source: D:\project\GO\gowork\src\datastream\view\template\dashboard.html
// DO NOT EDIT!
package gotemplate

import (
	"my/ar/399/datastream/datalayer"
	"io"

	"github.com/shiyanhui/hero"
)

func DashboardHandler(u datalayer.UserLogin, w io.Writer) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>
<html lang="fa" dir="rtl">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/StaticUI/Images/icon.ico" type="image/ico" />

    <title>بـاداده | 
      `)
	_buffer.WriteString(`
    پیش خوان
`)

	_buffer.WriteString(`
    </title>

    <!-- Bootstrap -->
    <link href="/StaticUI/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/StaticUI/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/StaticUI/vendors/nprogress/nprogress.css" rel="stylesheet">
    `)
	_buffer.WriteString(`
    <!-- iCheck -->
    <link href="/StaticUI/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
`)

	_buffer.WriteString(`

    <!-- Custom Theme Style -->
    <link href="/StaticUI/build/css/custom.min.css" rel="stylesheet">
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 right_col menu_fixed">
          <div class="right_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="/Dashboard" class="site_title">
                <img style="padding: 6px 10px 6px 7px;height: 38px; width: auto;display: inline;" src="/StaticUI/Images/logo.png" >
                <span> بـاداده </span></a>
            </div>
            <div class="clearfix"></div>
            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <ul class="nav side-menu">
                  <li><a href="/Dashboard"><i class="fa fa-home"></i>پیش خوان</a>
                  </li>
                  <li><a><i class="fa fa-tasks"></i>سرویس ها<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Services">مشاهده سرویس های ایجاد شده</a></li>
                      <li><a href="/NewService">ایجاد سرویس جدید</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-dollar"></i>اعتبار حساب<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Credit">مشاهده اعتبار حساب</a></li>
                      <li><a href="/IncreaseCredit">افزایش اعتبار حساب</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-envelope"></i>پیام ها<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Messages">مشاهده اعلان ها</a></li>
                      <li><a href="/ContactUs">ارتباط با ما</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-user"></i>حساب کاربری<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Settings">تنظیمات حساب کاربری</a></li>
                      <li><a href="/Logout">خروج</a></li>
                    </ul>
                  </li>
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-left">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    `)
	hero.EscapeHTML(u.Fname+" "+u.Lname, _buffer)

	_buffer.WriteString(`            
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">                     
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="left_col" role="main">
          `)
	_buffer.WriteString(`
<div class="">
  <div class="row">
    <div class="bs-example" data-example-id="simple-jumbotron">
      <div class="jumbotron">
        <h1>سلام  `)
	hero.EscapeHTML(u.Fname, _buffer)
	_buffer.WriteString(`</h1>
      </br>
        <h1>به سامانه بـاداده خوش‌آمدید</h1>
        <p>مژده! مژده! به علت افتتاح این سامانه، در حال حاضر تمامی سرویس‌های این سامانه رایگان می‌باشد.</p>
      </div>
    </div>
  </div>
  <div class="row tile_count">
    <a href="/Services">
      <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 tile_stats_count">
        <span class="count_top"><i class="fa fa-tasks"></i>  سرویس‌های ایجاد شده را مشاهده کن </span>
        <div class="count">مشاهده سرویس‌ها</div>
        <div class="clearfix"></div><span class="count_bottom"></span>
      </div>
    </a>
    <a href="/NewService">
      <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 tile_stats_count">
        <span class="count_top"><i class="fa fa-plus"></i>  به صورت رایگان سرویس جدید ایجاد کن</span>
        <div class="count">ایجاد سرویس جدید</div>
        <div class="clearfix"></div><span class="count_bottom"></span>
      </div>
    </a>
    <a href="/Credit">
      <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 tile_stats_count">
        <span class="count_top"><i class="fa fa-usd"></i>  اعتبار حساب را مدیریت کن </span>
        <div class="count">اعتبار حساب</div>
        <div class="clearfix"></div><span class="count_bottom"></span>
      </div>
    </a>
    <a href="/Messages">
      <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 tile_stats_count">
        <span class="count_top"><i class="fa fa-envelope"></i>  پیام‌ها و اعلان‌ها را مشاهده کن </span>
        <div class="count">پیام ها</div>
        <div class="clearfix"></div><span class="count_bottom"></span>
      </div>
    </a>
    <a href="/ContactUs">
      <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 tile_stats_count">
        <span class="count_top"><i class="fa fa-tty"></i>  با ما در ارتباط باش </span>
        <div class="count">ارتباط با ما</div>
        <div class="clearfix"></div><span class="count_bottom"> </span>
      </div>
    </a>
    <a href="/Settings">
      <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 tile_stats_count">
        <span class="count_top"><i class="fa fa-user"></i>  حساب کاربری را مدیریت کن</span>
        <div class="count">حساب کاربری</div>
        <div class="clearfix"></div><span class="count_bottom"> </span>
      </div>
    </a>
  </div>
  <div class="row">

  </div>
</div>
`)

	_buffer.WriteString(`
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-left">
            بـاداده » سامانه برخط خوشه‌بندی داده‌های جریانی
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
    </div>

    <!-- jQuery -->
    <script src="/StaticUI/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/StaticUI/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="/StaticUI/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="/StaticUI/vendors/nprogress/nprogress.js"></script>
    `)
	_buffer.WriteString(`
  <!-- bootstrap-progressbar -->
  <script src="/StaticUI/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
`)

	_buffer.WriteString(`

    <!-- Custom Theme Scripts -->
    <script src="/StaticUI/build/js/custom.min.js"></script>
    `)
	_buffer.WriteString(`
    
  </body>
</html>`)
	w.Write(_buffer.Bytes())

}
