// Code generated by hero.
// source: D:\project\GO\gowork\src\datastream\view\template\newservice.html
// DO NOT EDIT!
package gotemplate

import (
	"my/ar/399/datastream/datalayer"
	"io"

	"github.com/shiyanhui/hero"
)

func AddServiceHandler(u datalayer.UserLogin, w io.Writer) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>
<html lang="fa" dir="rtl">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/StaticUI/Images/icon.ico" type="image/ico" />

    <title>بـاداده | 
      `)
	_buffer.WriteString(`
    ایجاد سرویس‌ جدید
`)

	_buffer.WriteString(`
    </title>

    <!-- Bootstrap -->
    <link href="/StaticUI/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/StaticUI/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/StaticUI/vendors/nprogress/nprogress.css" rel="stylesheet">
    `)
	_buffer.WriteString(`
    <!-- iCheck -->
    <link href="/StaticUI/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
`)

	_buffer.WriteString(`

    <!-- Custom Theme Style -->
    <link href="/StaticUI/build/css/custom.min.css" rel="stylesheet">
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 right_col menu_fixed">
          <div class="right_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="/Dashboard" class="site_title">
                <img style="padding: 6px 10px 6px 7px;height: 38px; width: auto;display: inline;" src="/StaticUI/Images/logo.png" >
                <span> بـاداده </span></a>
            </div>
            <div class="clearfix"></div>
            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <ul class="nav side-menu">
                  <li><a href="/Dashboard"><i class="fa fa-home"></i>پیش خوان</a>
                  </li>
                  <li><a><i class="fa fa-tasks"></i>سرویس ها<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Services">مشاهده سرویس های ایجاد شده</a></li>
                      <li><a href="/NewService">ایجاد سرویس جدید</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-dollar"></i>اعتبار حساب<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Credit">مشاهده اعتبار حساب</a></li>
                      <li><a href="/IncreaseCredit">افزایش اعتبار حساب</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-envelope"></i>پیام ها<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Messages">مشاهده اعلان ها</a></li>
                      <li><a href="/ContactUs">ارتباط با ما</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-user"></i>حساب کاربری<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Settings">تنظیمات حساب کاربری</a></li>
                      <li><a href="/Logout">خروج</a></li>
                    </ul>
                  </li>
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-left">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    `)
	hero.EscapeHTML(u.Fname+" "+u.Lname, _buffer)

	_buffer.WriteString(`            
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">                     
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="left_col" role="main">
          `)
	_buffer.WriteString(`
    <div class="">
        <div class="page-title">
            <div class="title_right">
              <h3>ایجاد سرویس‌ جدید</h3>
            </div>
        </div>

        <div class="clearfix"></div>
        <div class="row">

          <div class="col-md-6 col-sm-6 col-xs-12">
              <div class="x_panel">
                  <div class="x_title">
                      <h2>ایجاد سرویس ساختاریافته</h2>
                      <ul class="nav navbar-left panel_toolbox">    
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                      </ul>
                      <div class="clearfix"></div>
                  </div>
                <div class="x_content">
                  <h3>سرویس ساختاریافته سرویسی است که شما در ابتدای ایجاد سرویس 
                      شما ساختار داده‌های ورودی را تعیین می‌کنید.</h3>
                  <br>
                  <h2>این سرویس مناسب زمانی است که شما نیاز دارید داده‌ها را 
                      به صورت برخط در قالب json به سرور ارسال کنید، 
                      پس لازم است ساختار فایل json از جمله تعداد و نام متغیرهای ورودی را از قبل مشخص کنید.
                  </h2>
                  <br>
                  <div class="clearfix"></div>
                  <a href="/AddStructuredService">
                    <button type="button" class="btn btn-default btn-lg btn-block">ایجاد سرویس ساختاریافته</button>
                  </a>
                </div>
              </div>
          </div>

          <div class="col-md-6 col-sm-6 col-xs-12">
              <div class="x_panel">
                  <div class="x_title">
                      <h2>ایجاد سرویس بدون ساختار</h2>
                      <ul class="nav navbar-left panel_toolbox">    
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                      </ul>
                      <div class="clearfix"></div>
                  </div>
                <div class="x_content">
                  <h3>سرویس بدون ساختار سرویسی است که شما برای داده‌های ورودی ساختاری تعیین نمی‌کنید.</h3>
                  <br>
                  <h2>این سرویس مناسب زمانی است که شما فایلی از جدول داده‌ها (csv.)
                      دارید و می‌خواهید فقط داده‌های این فایل را خوشه بندی کنید.
                      اگر تمام داده‌های شما در یک فایل موجود است این نوع سرویس به شما کمک می‌کند تا
                      سریع‌تر سرویس خود را راه‌اندازی کنید.
                  </h2>
                  <br>
                  <div class="clearfix"></div>
                  <a href="/AddUnStructuredService">
                    <button type="button" class="btn btn-default btn-lg btn-block">ایجاد سرویس بدون ساختار</button>
                  </a>
                </div>
              </div>
          </div>

          <div class="clearfix"></div>

        </div>

        <div class="row">

          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                  <h2>راهنمای سرویس ها</h2>
                  <ul class="nav navbar-left panel_toolbox">    
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
              </div>

              <div class="x_content">
                  <h2>سرویس ساختاریافته:</h2>
                  
                  <p>در این سرویس شما با انجام چند مرحله می‌توانید سرویس خود را راه اندازی کنید.
                    که شامل مراحل زیر است. <br>
                     1.تعیین مشخصات سرویس (نام سرویس)، 
                     2.تعیین ساختار داده سرویس (تعیین نام متغیرهای ورودی)، 
                     3.تعیین پارامترهای الگوریتم خوشه‌بندی، 
                     4.تعیین میزان اعتبار سرویس، 
                     5.تعیین وضعیت سرویس (فعال سازی و تنطیم تاریخ انقضا) <br>
                     بدین ترتیب سرویس شما فعال می‌شود و با در اختیار قرار گرفتن یک توکن و تنظیم آن در header درخواست خود می‌توانید داده‌های خود را در قالب فرمت json به سرور ارسال کنید. 
                    </p>
                  <div class="clearfix"></div>
                  <br><br>
                  <h2>سرویس بدون ساختار:</h2>
                  
                  <p>در این سرویس شما در ابتدا فایلی با فرمت csv در سامانه بارگذاری می‌کنید سپس با نمایش چند سطر اول این فایل شما می‌توانید با اعمال فیلتر بر روی ستون‌ها مشخص کنید که کدام ستون‌ها بررسی شوند و کدام ستون‌ها نادیده گرفته شوند.
                    در گام بعدی شما با تعیین مقدار شعاع epsilon میکرو خوشه ها و هم چنین شعاع epsilon الگوریتم DBSCAN می‌توانید شروع به خوشه‌بندی داده‌ها نمایید. 
                  </p>
                  <div class="clearfix"></div>
                  <br><br>
                  <h2>پارامترهای الگوریتم خوشه‌بندی:</h2>
                  <p><ul><li><strong>شعاع epsilon میکرو خوشه ها :</strong>داده های شما قبل از خوشه بندی در میکروخوشه‌هایی دسته بندی می‌شوند. این پارامتر تعیین‌کننده‌ی مقدار شعاع epsilon این میکرو خوشه‌ها می‌باشد. </li>
                    <br><li><strong>شعاع epsilon الگوریتم DBSCAN :</strong>داده های شما بعد از دسته‌بندی در میکروخوشه‌ها توسط الگوریتم DBSCAN خوشه‌بندی می‌شوند. این پارامتر تعیین‌کننده‌ی مقدار شعاع  epsilon الگوریتم DBSCAN می‌باشد.</li>
                    <br><li><strong>ضریب اهمیت داده قدیمی :</strong> این پارامتر اهمیت داده قدیمی را مشخص می‌کند هر چه قدر این مقدار بیشتر باشد اهمیت داده‌های قدیمی کمتر است. این پارامتر باید بزرکتر از صفر باشد.</li>
                    </ul>
                  </p>
              </div>

            </div>

          </div>

        </div>
    </div>
`)

	_buffer.WriteString(`
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-left">
            بـاداده » سامانه برخط خوشه‌بندی داده‌های جریانی
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
    </div>

    <!-- jQuery -->
    <script src="/StaticUI/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/StaticUI/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="/StaticUI/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="/StaticUI/vendors/nprogress/nprogress.js"></script>
    `)
	_buffer.WriteString(`
  <!-- bootstrap-progressbar -->
  <script src="/StaticUI/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
`)

	_buffer.WriteString(`

    <!-- Custom Theme Scripts -->
    <script src="/StaticUI/build/js/custom.min.js"></script>
    `)
	_buffer.WriteString(`
    
  </body>
</html>`)
	w.Write(_buffer.Bytes())

}
