// Code generated by hero.
// source: D:\project\GO\gowork\src\datastream\view\template\page_404.html
// DO NOT EDIT!
package gotemplate

import (
	"io"

	"github.com/shiyanhui/hero"
)

func PageNotFoundHandler(w io.Writer) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`

<!DOCTYPE html>
<html lang="fa" dir="rtl">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>بـاداده | 404 Error</title>

    <!-- Bootstrap -->
    <link href="/StaticUI/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/StaticUI/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/StaticUI/vendors/nprogress/nprogress.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="/StaticUI/build/css/custom.min.css" rel="stylesheet">
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <!-- page content -->
        <div class="col-md-12">
          <div class="col-middle">
            <div class="text-center text-center">
              <h1 class="error-number">404</h1>
              <h2>متاسفانه این صفحه یافت نشد. به آدرسی که وارد کردید دقت کنید</h2>
              <p>اگر این صفحه قبلا وجود داشته و یا اگر از طریق لینکی از درون سایت به این صفحه ارجاع داده شدید، لطفا <a href="/ContactUs"> به ما گزارش دهید</a>.
              </p>
            </div>
          </div>
        </div>
        <!-- /page content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="/StaticUI/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/StaticUI/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="/StaticUI/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="/StaticUI/vendors/nprogress/nprogress.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="/StaticUI/build/js/custom.min.js"></script>
  </body>
</html>`)
	w.Write(_buffer.Bytes())

}
