// Code generated by hero.
// source: D:\project\GO\gowork\src\datastream\view\template\signup.html
// DO NOT EDIT!
package gotemplate

import (
	"io"

	"github.com/shiyanhui/hero"
)

func SignupHandler(w io.Writer) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>
<html lang="fa" dir="rtl">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/StaticUI/Images/icon.ico" type="image/ico" />

    <title>بـاداده | 
      `)
	_buffer.WriteString(`
    ثبت نام در سامانه
`)

	_buffer.WriteString(`
    </title>

    <!-- Bootstrap -->
    <link href="/StaticUI/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/StaticUI/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/StaticUI/vendors/nprogress/nprogress.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="/StaticUI/build/css/custom.min.css" rel="stylesheet">
    <style>
        .full-height{
            height: 100vh;
        }
        body{
            height: 100vh;
        }
        #info{
            height: 100%;
            padding-left: 0px;
            padding-right: 0px;
        }
        #title{
            font-size: 60px;
            font-weight: 800;
            text-shadow: 3px 4px 0  rgb(50,110,232);
            margin-bottom: 20px;
            color: white;
        }
        #sub-title{
            font-size: 24px;
            font-weight: 600;
            color: white;
        }
        .mycontainer11{
            margin-right: auto;
            margin-left: auto;
            max-width: 97.7%;
            height: 100%;
        }  
    </style>
    `)
	_buffer.WriteString(`
    <style>
    
        #login{
            height: 100%;
            background-color: #f5f7fa;
        }
        .form-control{
            font-size: 15px;
        }
        #singuptxt{
            padding-top: 18px;
    
        }
        #login-btn{
            font-weight: 600;
            font-size: 15px;
        }
        #vorod-lbl{
            font-size: 40px;
            font-weight: 700;
            padding-bottom: 20px;
            color:#2a3f54;
        }
        #divErr{
            font-size: 15px;
            color: red;
            font-family: 'BYekan';
            text-align: center;
        }
    </style>
`)

	_buffer.WriteString(`
</head>
<body style="overflow: hidden;">
    <div class="mycontainer11">
        <div class="row full-height">
            `)
	_buffer.WriteString(`
    <div id="login" class="col-lg-4 col-md-4 col-sm-12 col-xs-12 full-height">
        <div >

            <br><br>
            <div class="col-lg-12 col-md-offset-0 col-md-12 col-sm-6 col-sm-offset-3 col-xs-6 col-xs-offset-3">
                <form id="login-form">
                    <h1 id="vorod-lbl"class="text-center">ثبت نام</h1>
                    <div id="divErr">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="fname" placeholder="نام">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="lname" placeholder="نام خانوادگی">
                    </div>
                    <br>
                    <div class="form-group">
                    <input type="email" class="form-control" name="email" placeholder="پست الکترونیکی">
                    </div>
                    <div class="form-group">
                    <input type="password" class="form-control" name="password" placeholder="رمز عبور">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" name="repassword" placeholder="تکرار رمز عبور">
                    </div>
                    <button id="login-btn" name ="send" type="submit" class="btn btn-block btn-dark">ثبت نام</button>
                    <div id="singuptxt" class="form-subnote verfication-subnote text-center">
                        <span class="form-subnote__label">
                            حساب کاربری دارید؟
                        </span>
                        <a class="form-subnote__link verfication-link" href="\Login">
                            <strong> وارد شوید</strong>
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
`)

	_buffer.WriteString(`
            <div id="info" class="col-lg-8 col-md-8 hidden-sm hidden-xs" >
                <img src="/StaticUI/Images/info.png"  class="img-responsive" alt="Responsive image">
                <h2 id="title" class="text-center">
                باداده</h2>
                <h6 id="sub-title" class="text-center">  
                سامانه برخط خوشه بندی داده‌های جریانی
                </h6>
            </div>
            
        </div>
    </div>

    <!-- jQuery -->
    <script src="/StaticUI/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/StaticUI/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="/StaticUI/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="/StaticUI/vendors/nprogress/nprogress.js"></script>
    `)
	_buffer.WriteString(`
    <script>
        $("#login-form").on("submit", function (e) {
            e.preventDefault();
            const myForm = document.getElementById("login-form");
            const data = $("#login-form").serialize();
            var $self = $(this);
            $.ajax({
                url: "/Login",
                type: "POST",
                data : data,
            }).success( function(res){
                if (res.errstate==true){
                    document.getElementById("divErr").innerHTML = res.errmsg;
                }else{
                    window.location.replace(res.errmsg);
                }
            });
        });
    </script>
`)

	_buffer.WriteString(`

    <!-- Custom Theme Scripts -->
    <script src="/StaticUI/build/js/custom.min.js"></script>
</body>
</html>`)
	w.Write(_buffer.Bytes())

}
