// Code generated by hero.
// source: D:\project\GO\gowork\src\datastream\view\template\viewresult.html
// DO NOT EDIT!
package gotemplate

import (
	"my/ar/399/datastream/controller/clustering/denstream"
	"my/ar/399/datastream/controller/utility/ptime"
	"my/ar/399/datastream/datalayer"
	"fmt"
	"io"

	"github.com/shiyanhui/hero"
)

func ViewResultHandler(u datalayer.UserLogin, sid string, serv datalayer.Service, clu denstream.USresult, w io.Writer) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>
<html lang="fa" dir="rtl">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/StaticUI/Images/icon.ico" type="image/ico" />

    <title>بـاداده | 
      `)
	_buffer.WriteString(`
    نتیجه خوشه بندی
`)

	_buffer.WriteString(`
    </title>

    <!-- Bootstrap -->
    <link href="/StaticUI/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/StaticUI/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/StaticUI/vendors/nprogress/nprogress.css" rel="stylesheet">
    `)
	_buffer.WriteString(`
    <!-- iCheck -->
    <link href="/StaticUI/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
`)

	_buffer.WriteString(`

    <!-- Custom Theme Style -->
    <link href="/StaticUI/build/css/custom.min.css" rel="stylesheet">
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 right_col menu_fixed">
          <div class="right_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="/Dashboard" class="site_title">
                <img style="padding: 6px 10px 6px 7px;height: 38px; width: auto;display: inline;" src="/StaticUI/Images/logo.png" >
                <span> بـاداده </span></a>
            </div>
            <div class="clearfix"></div>
            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <ul class="nav side-menu">
                  <li><a href="/Dashboard"><i class="fa fa-home"></i>پیش خوان</a>
                  </li>
                  <li><a><i class="fa fa-tasks"></i>سرویس ها<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Services">مشاهده سرویس های ایجاد شده</a></li>
                      <li><a href="/NewService">ایجاد سرویس جدید</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-dollar"></i>اعتبار حساب<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Credit">مشاهده اعتبار حساب</a></li>
                      <li><a href="/IncreaseCredit">افزایش اعتبار حساب</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-envelope"></i>پیام ها<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Messages">مشاهده اعلان ها</a></li>
                      <li><a href="/ContactUs">ارتباط با ما</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-user"></i>حساب کاربری<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/Settings">تنظیمات حساب کاربری</a></li>
                      <li><a href="/Logout">خروج</a></li>
                    </ul>
                  </li>
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-left">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    `)
	hero.EscapeHTML(u.Fname+" "+u.Lname, _buffer)

	_buffer.WriteString(`            
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">                     
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="left_col" role="main">
          `)
	_buffer.WriteString(`
  <div class="">
      <div class="page-title">
          <div class="title_right">
            <h3>نتیجه خوشه بندی داده‌ها</h3>
          </div>
      </div>
      <div class="row">

        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
                <h2>اطلاعات سرویس</h2>
                <ul class="nav navbar-left panel_toolbox">    
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
            </div>

            <div class="col-md-5 col-lg-4 col-sm-5">              
              <h2>نام سرویس:</h2>
              <h3>`)
	hero.EscapeHTML(serv.Name.String, _buffer)
	_buffer.WriteString(`</h3>
              <br>
              <h2>تاریخ ایجاد سرویس:</h2>
              <h3>`)
	hero.EscapeHTML(ptime.ToPersian(serv.Created.Time), _buffer)
	_buffer.WriteString(`</h3>
              <br>             
              <h2>اعتبار زمانی سرویس:</h2>
              `)
	if serv.Credit.Int32 == -1 {
		_buffer.WriteString(`
                <h3>سرویس رایگان</h3>  
              `)
	} else {
		_buffer.WriteString(`
                <h3>`)
		hero.EscapeHTML(fmt.Sprint(serv.Credit.Int32), _buffer)
		_buffer.WriteString(` (ساعت)</h3>  
              `)
	}
	_buffer.WriteString(`                       
            </div>
            <div class="col-md-7 col-lg-8 col-sm-7">
              <!-- blockquote -->
              <blockquote>
                <h3>تعداد داده های بررسی شده:</h3>
                <h1>`)
	hero.EscapeHTML(fmt.Sprint(clu.NumData), _buffer)
	_buffer.WriteString(`</h1>
                <br>
                <h3>تعداد میکرو خوشه های ایجادشده:</h3>
                <h1>`)
	hero.EscapeHTML(fmt.Sprint(clu.NumMicro), _buffer)
	_buffer.WriteString(`</h1>
                <br>
                <h3>تعداد خوشه های ایجادشده:</h3>
                <h1>`)
	hero.EscapeHTML(fmt.Sprint(len(clu.Clusters)), _buffer)
	_buffer.WriteString(`</h1> 
                
              </blockquote>

            </div>
            
          </div>

        </div>

      </div>
      <div class="clearfix"></div>
      `)
	if serv.HDcount.Int32 == 2 {
		_buffer.WriteString(`
        <!-- نمودار خوشه های ایجاد شده -->
        <div class="row">

          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                  <h2>نمودار خوشه های ایجاد شده</h2>
                  <ul class="nav navbar-left panel_toolbox">    
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
              </div>

              <div class="x_content">
                  <a>خوشه های متفاوت با رنگ های متفاوت جدا شده اند. هر نقطه در نمودار نشان دهنده
                    یک میکرو خوشه است که شعاع آن با میله‌های خطا مشخص شده است.
                  </a>
                  <br>
                  <img src=`)
		hero.EscapeHTML("/Plot/c-"+sid+".png", _buffer)
		_buffer.WriteString(` class="img-responsive" alt="Responsive image">
              </div>

            </div>

          </div>

        </div>
        <div class="clearfix"></div>
      `)
	}
	_buffer.WriteString(`

      <div class="row">

        <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>پیدا کردن خوشه یک داده</h2>
                    <ul class="nav navbar-left panel_toolbox">    
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
              <div class="x_content"> 
                <div class="accordion" id="accordion" role="tablist" aria-multiselectable="true">
                  <div class="panel">
                    <a class="panel-heading collapsed" role="tab" id="headingTwo" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                      <h4 class="panel-title">راهنما</h4>
                    </a>
                    <div id="collapseTwo" class="panel-collapse collapse" role="tabpane" aria-labelledby="headingTwo">
                      <div class="panel-body">
                        <p><strong>راهنمای پیدا کردن خوشه یک داده</strong>
                        </p>
                        در این قسمت شما می‌توانید با وارد کردن مقادیر یک داده، خوشه‌ای که 
                        این داده متعلق به آن است را پیدا کنید.
                        <br>
                        در صورتی که یک داده متعلق به چندین خوشه باشد، تمام خوشه‌هایی که این داده میتواند متعلق
                        به آن باشد نمایش داده می‌شوند.
                        
                      </div>
                    </div>
                  </div>                  
                </div>               
                <br>
                <form id="form" novalidate>
                  <span class="section">داده ورودی</span>
                  `)
	i := 0
	for _, v := range clu.HdrName {
		_buffer.WriteString(`
                    <div class="form-group">
                      <label for="data0_`)
		hero.EscapeHTML(fmt.Sprint(i), _buffer)
		_buffer.WriteString(`">`)
		hero.EscapeHTML(v, _buffer)
		_buffer.WriteString(` : </label>
                      <input dir="ltr" class="form-control" type="number" id="data0_`)
		hero.EscapeHTML(fmt.Sprint(i), _buffer)
		_buffer.WriteString(`" name="data0_`)
		hero.EscapeHTML(fmt.Sprint(i), _buffer)
		_buffer.WriteString(`"  step="1">
                    </div>
                    `)
		i++
	}
	_buffer.WriteString(`
                <input type="hidden" name="count" value="`)
	hero.EscapeHTML(fmt.Sprint(len(clu.HdrName)), _buffer)
	_buffer.WriteString(`">
                
                <div class="ln_solid col-md-4 col-sm-4 col-xs-12"></div>
                <div>               
                  <a>
                    <button type="submit" class="btn btn-lg btn-primary btn-block">  یافتن خوشه  </button>
                  </a>
                </div>
                </form>
                <div class="">
                  <div id="findclu" class="product_price"></div>
                </div>
              </div>
            </div>
        </div>

        <div class="col-md-8 col-sm-8 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>بررسی وضعیت دو داده</h2>
                    <ul class="nav navbar-left panel_toolbox">    
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
              <div class="x_content"> 
                <div class="accordion" id="accordion1" role="tablist" aria-multiselectable="true">
                  <div class="panel">
                    <a class="panel-heading collapsed" role="tab" id="headingTwo1" data-toggle="collapse" data-parent="#accordion1" href="#collapseTwo1" aria-expanded="false" aria-controls="collapseTwo">
                      <h4 class="panel-title">راهنما</h4>
                    </a>
                    <div id="collapseTwo1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                      <div class="panel-body">
                        <p><strong>راهنمای بررسی وضعیت دو داده</strong>
                        </p>
                        در این قسمت شما می‌توانید با وارد کردن مقادیر دو داده متفاوت، به وضعیت این دو داده 
                        نسبت به هم پی ببرید.                  
                        <br>
                        وضعیت دو داده نسبت به هم شامل متعلق بودن یا نبودن به یک خوشه
                        و همچنین متعلق بودن یا نبودن به یک میکرو خوشه می‌باشد.
                        
                      </div>
                    </div>
                  </div>                  
                </div>               
                <br>
                <form id="form1" novalidate>
                  <div class="col-md-6 col-sm-6 col-xs-12" style="border-left: 2px solid #dbdbdb;">
                    <span class="section">داده اول</span>
                    `)
	j1 := 0
	for _, v := range clu.HdrName {
		_buffer.WriteString(`
                      <div class="form-group">
                        <label for="data0_`)
		hero.EscapeHTML(fmt.Sprint(j1), _buffer)
		_buffer.WriteString(`">`)
		hero.EscapeHTML(v, _buffer)
		_buffer.WriteString(` : </label>
                        <input class="form-control" dir="ltr" type="number" id="data1_`)
		hero.EscapeHTML(fmt.Sprint(j1), _buffer)
		_buffer.WriteString(`" name="data1_`)
		hero.EscapeHTML(fmt.Sprint(j1), _buffer)
		_buffer.WriteString(`"  step="1">
                      </div>
                      `)
		j1++
	}
	_buffer.WriteString(`
                  </div>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <span class="section">داده دوم</span>
                    `)
	j2 := 0
	for _, v := range clu.HdrName {
		_buffer.WriteString(`
                      <div class="form-group">
                        <label for="data0_`)
		hero.EscapeHTML(fmt.Sprint(j2), _buffer)
		_buffer.WriteString(`">`)
		hero.EscapeHTML(v, _buffer)
		_buffer.WriteString(` : </label>
                        <input class="form-control" dir="ltr" type="number" id="data2_`)
		hero.EscapeHTML(fmt.Sprint(j2), _buffer)
		_buffer.WriteString(`" name="data2_`)
		hero.EscapeHTML(fmt.Sprint(j2), _buffer)
		_buffer.WriteString(`"  step="1">
                      </div>
                        `)
		j2++
	}
	_buffer.WriteString(`
                  </div>
                <input type="hidden" name="count" value="`)
	hero.EscapeHTML(fmt.Sprint(len(clu.HdrName)), _buffer)
	_buffer.WriteString(`">
                
                <div class="ln_solid col-md-12 col-sm-12 col-xs-12"></div>
                <div class="col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12">               
                  <a href="/AddStructuredService">
                    <button type="submit" class="btn btn-lg btn-primary btn-block">  بررسی وضعیت  </button>
                  </a>
                </div>
                </form>       
                <div class="">
                  <div id="checkdata" class="product_price"></div>
                </div>
                
              </div>
            </div>
        </div>

        <div class="clearfix"></div>

      </div>

  </div>
`)

	_buffer.WriteString(`
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-left">
            بـاداده » سامانه برخط خوشه‌بندی داده‌های جریانی
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
    </div>

    <!-- jQuery -->
    <script src="/StaticUI/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/StaticUI/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="/StaticUI/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="/StaticUI/vendors/nprogress/nprogress.js"></script>
    `)
	_buffer.WriteString(`
  <!-- bootstrap-progressbar -->
  <script src="/StaticUI/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
`)

	_buffer.WriteString(`

    <!-- Custom Theme Scripts -->
    <script src="/StaticUI/build/js/custom.min.js"></script>
    `)
	_buffer.WriteString(`
  <script>
    $("#form").on("submit", function (e) {
        e.preventDefault();
        const myForm = document.getElementById("form");
        const data = $("#form").serialize();
        var $self = $(this);
        $.ajax({
            url: window.location.pathname+"/FindCluster",
            type: "POST",
            data : data,
        }).success( function(res){
            document.getElementById("findclu").innerHTML = res;
            
        });
    });
    $("#form1").on("submit", function (e) {
        e.preventDefault();
        const myForm = document.getElementById("form1");
        const data = $("#form1").serialize();
        var $self = $(this);
        $.ajax({
            url: window.location.pathname+"/CheckData",
            type: "POST",
            data : data,
        }).success( function(res){
            document.getElementById("checkdata").innerHTML = res;            
        });
    });
</script>
`)

	_buffer.WriteString(`
    
  </body>
</html>`)
	w.Write(_buffer.Bytes())

}
